In [5]:
import numpy as np

In [8]:
A = np.array([[2,4,8],[2,-1,5],[-8,5,2]])
B = np.array([[1,3,9],[3,-2,6],[9,4,1]])
C = np.array([[3,2],[-1,2],[3,5]])
D = np.array([[1,7,5],[2,4,5],[1,-1,4]])
E = (A+B)
F =2*(A)
G = A @ C

In [9]:
print(f"Matrix A 3x3: \n{A}")
print(f" Matrix B 3x3: \n{B}")
print(f"Matrix C 3x2: \n{C}")
print(f"Matrix D 3x3: \n{D}")

Matrix A 3x3: 
[[ 2  4  8]
 [ 2 -1  5]
 [-8  5  2]]
 Matrix B 3x3: 
[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]
Matrix C 3x2: 
[[ 3  2]
 [-1  2]
 [ 3  5]]
Matrix D 3x3: 
[[ 1  7  5]
 [ 2  4  5]
 [ 1 -1  4]]


In [10]:
f = 2*(A)

print(f"perkalian 2 * matrix f =\n{f}")

perkalian 2 * matrix f =
[[  4   8  16]
 [  4  -2  10]
 [-16  10   4]]


In [1]:
import numpy as np
a = np.array ([[2,3,5],[7,8,1],[9,2,6]])
b = np.array ([[5,7],[1,9],[4,7]])
hasil = np.dot (a,b)
print(hasil)

[[ 33  76]
 [ 47 128]
 [ 71 123]]
